name: blank
on: push

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Show git job
        run: |
          echo "This is the git job"
          git --version || true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "This is the build job"
